language: node_js
node_js:
- "8"

script: npm run build

deploy:
  fqdn: trellostory.deployable.site
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
